### ISSUE TITLE
Create Initial User Stories

### ISSUE THREAD

**Issue by bazakeliad** [bazakeliad/App-Development-Project#2]
### Overview
Identify and document key features and functionalities needed for the web app.
Prioritize these user stories to guide the development process.

Use this [Requirements file](https://moodle.colman.ac.il/pluginfile.php/121923/mod_resource/content/0/Project.docx%20%285%29.pdf) To cover all needed features. In addition, check out some apps form past semesters.

### DOD
- [x] Create a README file which will include all needed features and in which order they should be developed

### Merge Requests

**Comment by BenEpstein** [comment]
HI Melech,

Just wanted to give my 2 cents here... 
I think from this task's conclusions and findings, we will start creating actual **development tasks**. This is why we need to understand the best way we can divide tasks to work in parallel and to avoid conflicts.

**Comment by bazakeliad** [comment]
> HI Melech,
> 
> Just wanted to give my 2 cents here... 
> I think from this task's conclusions and findings, we will start creating actual **development tasks**. This is why we need to understand the best way we can divide tasks to work in parallel and to avoid conflicts. 
>  

Great point, and I completely agree. We should definitely focus on task division to ensure parallel work without conflicts. I’m more than **willing to help out** with this process if needed. Let’s make sure we have a solid plan in place, so we can start to program **as soon as** you finish this task🚀

**Comment by bazakeliad** [comment]
@itay55 can you please provide a quick update on the status of the task?

**Comment by itay55** [comment]
DONE !!!!
סיימתי !!!

**Comment by itay55** [comment]
look here [requirments file](https://github.com/bazakeliad/App-Development-Project/wiki/%D7%93%D7%A3-%D7%93%D7%A8%D7%99%D7%A9%D7%95%D7%AA)

**Comment by BenEpstein** [comment]
#### Review

Love it @itay55 . You gave some great ideas!

I think the last extra feature about a custom jersey may be too much for us.

I'll polish the final product and show @all as part of #7 

Moving to Done ✅
