### ISSUE TITLE
Create App Skeleton

### ISSUE THREAD

**Issue by bazakeliad** [bazakeliad/App-Development-Project#3]
### Overview
We need to decide and understand how the project should be structured.
An explained in the project instructions, we need to follow the MVC model.

### DOD
- [x] Understand the MVC development model
- [x] Understand where each component should be developed
    - [x] Frontend
    - [x] Backend
    - [x] DB
- [x] Create a README file to present findings and guide team members
### Merge Requests
<Insert your final PR>

**Comment by bazakeliad** [comment]
### The MVC Development Model:
- Model: Represents the data structure. It directly manages the data, logic, and rules of the application. The model is responsible for retrieving data from the database, handling business logic, and maintaining the state of the application.
- View: The user interface of the application. It displays data from the model to the user and sends user commands to the controller.
- Controller: Acts as an intermediary between the Model and the View. It listens to user input from the View, processes it (by interacting with the Model), and updates the View accordingly.

#### MVC design pattern (abstraction layer):
![image](https://github.com/user-attachments/assets/8d9739db-a676-4c35-83dd-c041e75a5240)

**Comment by bazakeliad** [comment]
Practically, we need to understand where each component should be developed.

**Frontend (View):**
This is where we’ll develop the user interface. It includes the HTML, CSS, and JavaScript files.

**Backend (Controller & Model):**
The controller will handle requests from the frontend, process them (using the model), and send the appropriate responses back. For our use case we'll use Express (for Node.js).

**Database (Model):**
The database stores the data that the model will use. The model will interact with the database to create, read, update, and delete data. For our use case we'll use MongoDB.

**Comment by bazakeliad** [comment]
I wrote a [README  file](https://github.com/bazakeliad/App-Development-Project/wiki/MVC-Model), please review it and let me know your thoughts 🙃

**Comment by bazakeliad** [comment]
This task was moved to 'Review' as it has reached its DOD.

**Comment by BenEpstein** [comment]
### Review

Looks great and well explained!

I have a few questions:
1. Are we sure working with mongoose is supported within our project's instruction guides?
2. How did you decide to use the `models/`, `controller/` and `view/` directory structure? Is it a well known structure? Is it a best practice? 
I think we may want to separate the MongoDB files to a separate `data/` directory to have better separation and to avoid conflicts. Moreover, I've seen suggestion for `content/` directory but I think its overkill for now and we'll add more if necessary.

**Comment by bazakeliad** [comment]
> ### Review
> 
> Looks great and well explained!
> 
> I have a few questions:
> 1. Are we sure working with mongoose is supported within our project's instruction guides?
> 2. How did you decide to use the `models`, `controller` and `view` directory structure? Is it a well known structure? Is it a best practice? 

1. The most common way is to use mongoose. But to honest, I have no idea if it's supported within our project's instruction guides.
As an alternative, we can use the native MongoDB driver (mongodb package) provides direct interaction with MongoDB without an abstraction layer like Mongoose. It offers more control over queries and database operations.

2. The choice to use the models, controllers, and views directory structure aligns with common best practices and is a well-known approach in web application development

Yet, this structure is "only the top of the iceberg", and we'll have much more folders that interacts with all MVC components.


Here is a short overview of MVC structure (using chat gpt 4.0)

### Project Structure Overview:

```plaintext
online-store/
│
├── config/                    # Configuration files (e.g., database, environment settings)
│
├── controllers/               # Handles incoming requests and interacts with models
│   ├── authController.js
│   ├── productController.js
│   └── userController.js
│
├── models/                    # Mongoose schemas and models for data
│   ├── Product.js
│   └── User.js
│
├── views/                     # HTML files for the user interface
│   ├── layouts/
│   ├── products/
│   └── auth/
│
├── public/                    # Static assets (CSS, JavaScript, images)
│   ├── css/
│   ├── js/
│   └── images/
│
├── routes/                    # Route definitions mapping URLs to controllers
│   ├── authRoutes.js
│   ├── productRoutes.js
│   └── userRoutes.js
│
├── services/                  # Business logic (e.g., email, payment processing)
│   └── authService.js
│
├── middleware/                # Middleware functions (e.g., authentication, error handling)
│
├── .env                       # Environment variables
├── .gitignore                 # Files to ignore in version control
├── app.js                     # Main application entry point
├── package.json               # Project dependencies and scripts
└── README.md                  # Project documentation
```

### Short Explanation:

- **`config/`**: Setup for database and general configuration.
- **`controllers/`**: Manages logic between the Model and View layers.
- **`models/`**: Mongoose schemas/models to interact with MongoDB.
- **`views/`**: HTML files for the UI.
- **`public/`**: Contains static files like CSS, JS, and images.
- **`routes/`**: Defines URL paths and links them to controller actions.
- **`services/`**: Encapsulates business logic like authentication.
- **`middleware/`**: Functions that process requests before reaching controllers.
- **`app.js`**: Initializes the application and starts the server.

In addition, there are lots of articles about MVC best practices in Medium. Take a look at them😉

**Comment by BenEpstein** [comment]
Yeah, I think it's overkill to start with...I like the 3 dir structure you suggested to kick off.  I updated my review comment btw. what do you think?

**Comment by bazakeliad** [comment]
> Yeah, I think it's overkill to start with...I like the 3 dir structure you suggested to kick off.  I updated my review comment btw. what do you think?
> 

I agree that separating the MongoDB files into a data/ directory would improve the organization of our codebase and help avoid potential conflicts. However, I think  for our project it might be overkill (we should discuss it with the team). Regarding the content/ directory, I also think it’s better to keep things simple for now. We can always expand our structure later if the project grows in complexity or if we find the need for additional directories. 

Let’s proceed with talking and implementing if needed the data/ directory for now, and we can revisit the content/ idea if necessary.

**Comment by BenEpstein** [comment]
Sounds good. Closing this issue.
